# Generated by Django 3.2.8 on 2021-12-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_rename_lasrname_author_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='photos/authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='photos/books'),
        ),
    ]
