# Generated by Django 3.2.8 on 2021-12-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_auto_20211205_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookType',
            field=models.CharField(blank=True, choices=[('literature', 'LITERATURE'), ('scientific', 'SCIENTIFIC'), ('humanity', 'HUMANITY'), ('other', 'OTHER')], max_length=10, null=True),
        ),
    ]
